remote_theme: nicolas-van/bootstrap-4-github-pages
my_page.title: TS3WI-AdminLTE
my_page.description: TS3WI-AdminLTE is a clean, responsive theme based on AdminLTE for Teamspeak 3 Webinterface by Psychokiller.
