theme: jekyll-theme-cayman
title: TS3WI-AdminLTE
description: TS3WI-AdminLTE is a clean, responsive theme based on AdminLTE for Teamspeak 3 Webinterface by Psychokiller.

github:
    repository_url: https://github.com/REJack/TS3WI-AdminLTE/releases
